players:
  player0:
    working_dir: ../client/
    stdout: ./{timestamp}-stdout0.txt
    stderr: ./{timestamp}-stderr0.txt
  player1:
    working_dir: ../client/
    stdout: ./{timestamp}-stdout1.txt
    stderr: ./{timestamp}-stderr1.txt
  player2:
    working_dir: ../client/
    stdout: ./{timestamp}-stdout2.txt
    stderr: ./{timestamp}-stderr2.txt
  player3:
    working_dir: ../client/
    stdout: ./{timestamp}-stdout3.txt
    stderr: ./{timestamp}-stderr3.txt
  player4:
    working_dir: ../client/
    stdout: ./{timestamp}-stdout4.txt
    stderr: ./{timestamp}-stderr4.txt
controller:
  config_file: ./example_torcs_config.xml
  server_stdout: ./{timestamp}-server_out.txt
  server_stderr: ./{timestamp}-server_err.txt
  result_path: ../../../.torcs/results/
  driver_to_port:
     scr_server 1: 3001
     scr_server 2: 3002
     scr_server 3: 3003
     scr_server 4: 3004
     scr_server 5: 3005
     scr_server 6: 3006
     scr_server 7: 3007
     scr_server 8: 3008
     scr_server 9: 3009
     scr_server 10: 3010
rater:
  filename: ./example_ratings_file.csv
